-- COLOCAR O BANCO DE DADOS EM USO
USE SVIGUFO;

-- INSTITUICAO PADRAO QUE SERA UTILIZADA PARA O LOCAL DOS EVENTOS
-- ESPECIFICANDO OS CAMPOS QUE EU QUERO QUE SEJAM INSERIDOS
INSERT INTO INSTITUICOES (RAZAO_SOCIAL, NOME_FANTASIA, CNPJ, LOGRADOURO, CEP, UF, CIDADE) 
	VALUES (
		'RAZAO SOCIAL A', 'NOME FANTASIA A', '12345678901234', 'ALAMEDA BARAO DE LIMEIRA, 539', '12345678', 'SP', 'SAO PAULO' 
	);

-- SELECIONAR OS REGISTROS QUE FORAM INSERIDOS NAS TABELAS
-- LISTANDO OS REGISTROS DA TABELA DE INSTITUICOES
SELECT * FROM INSTITUICOES;

-- INSERINDO OS CAMPOS CONFORME AS COLUNAS DA TABELA
INSERT INTO TIPOS_EVENTOS VALUES ('MARKETING');

-- INSERINDO MAIS DE UM REGISTRO POR VEZ
INSERT INTO TIPOS_EVENTOS VALUES ('DESIGN'), ('TECNOLOGIA'), ('GAMES');

-- LISTANDO OS REGISTROS DA TABELA DE TIPOS DE EVENTOS
SELECT * FROM TIPOS_EVENTOS;

-- ENDERECOS DOS USUARIOS
INSERT INTO ENDERECOS VALUES (
	'Av. Paulista, 1578 - Bela Vista', '01310200', 'SP', 'São Paulo', '-23.561050', '-46.655946'
);

INSERT INTO ENDERECOS VALUES (
	'Av. Paulista, 1313 - Jardins', '01311923', 'SP', 'São Paulo', '-23.5635052', '-46.6566615'
);

SELECT * FROM ENDERECOS;

-- USUARIOS CADASTRADOS NO SISTEMA
INSERT INTO USUARIOS VALUES (
	'Helena Strada', 'helena.souza@sp.senai.br', '123456', 'ADMINISTRADOR', 1
);

INSERT INTO USUARIOS VALUES (
	'Fernando Henrique', 'fernando.guerra@corujasdev.com.br', '123456', 'COMUM', 2
);

SELECT * FROM USUARIOS;

-- CADASTRANDO UM NOVO EVENTO
INSERT INTO EVENTOS VALUES (
	-- YYYY-MM-DD HH:MI:SS
	-- https://www.w3schools.com/sql/func_sqlserver_convert.asp
	'Titulo A', 'Descricao A', CONVERT(DATETIME, '2019-03-18 19:00:00',120), GETDATE(), 1, 3, 2 
);

SELECT * FROM EVENTOS;

-- INSERINDO UM NOVO CONVITE
INSERT INTO CONVITES VALUES (1, 2);

SELECT * FROM CONVITES;