/* CRIAR UM BANCO DE DADOS - SINTAXE : CREATE DATABASE [NOME_BANCO] */
CREATE DATABASE SVIGUFO;

/* COLOCAR O BANCO DE DADOS CRIADO EM USO */
USE SVIGUFO;

CREATE TABLE TIPOS_EVENTOS (
    ID          INT IDENTITY PRIMARY KEY
    ,TITULO     VARCHAR(250) NOT NULL
);

CREATE TABLE EVENTOS (
    ID              INT IDENTITY PRIMARY KEY
    ,TITULO         VARCHAR(250) NOT NULL
    ,DESCRICAO      TEXT
    ,DATA_EVENTO    DATETIME
    ,DATA_CADASTRO  DATE
    ,ACESSO_LIVRE   BIT
    ,ID_TIPO_EVENTO INT -- FOREIGN KEY REFERENCES TIPOS_EVENTOS(ID)
    , FOREIGN KEY (ID_TIPO_EVENTO) REFERENCES TIPOS_EVENTOS(ID)
);

-- UNIQUE EMAIL
-- DEFAULT (0)

CREATE TABLE USUARIOS (
    ID              INT IDENTITY PRIMARY KEY
    ,NOME           VARCHAR(200) NOT NULL
    ,EMAIL          VARCHAR(254) NOT NULL
    ,SENHA          VARCHAR(100) NOT NULL
    ,TIPO_USUARIO   VARCHAR(50) NOT NULL
);

ALTER TABLE EVENTOS
ADD ID_PALESTRANTE INT FOREIGN KEY REFERENCES USUARIOS(ID);

CREATE TABLE ENDERECOS (
    ID              INT IDENTITY PRIMARY KEY
    ,LOGRADOURO     VARCHAR(200) NOT NULL
    ,CEP            CHAR(8) NOT NULL
    ,UF             CHAR(2) 
    ,CIDADE         VARCHAR(200) 
    ,LATITUDE       VARCHAR(20) NULL
    ,LONGITUDE      VARCHAR(20) NULL
);

ALTER TABLE USUARIOS
ADD ID_ENDERECO INT FOREIGN KEY REFERENCES ENDERECOS(ID);

CREATE TABLE CONVITES (
    ID_USUARIO          INT FOREIGN KEY REFERENCES USUARIOS(ID)
    ,ID_EVENTO          INT FOREIGN KEY REFERENCES EVENTOS(ID)
);