-- COLOCAR O BANCO DE DADOS EM USO
USE SVIGUFO;

-- SELECAO DE TODAS AS TABELAS
SELECT * FROM CONVITES;
SELECT * FROM ENDERECOS;
SELECT * FROM EVENTOS;
SELECT * FROM INSTITUICOES;
SELECT * FROM TIPOS_EVENTOS;
SELECT * FROM USUARIOS;

-- SELECIONANDO APENAS CAMPOS QUE EU QUERO
SELECT ID, TITULO, DESCRICAO, DATA_EVENTO FROM EVENTOS;
SELECT EMAIL, SENHA FROM USUARIOS;

-- CONTANDO QUANTOS REGISTROS EU TENHO ATUALMENTE NA TABELA
SELECT COUNT(*) FROM EVENTOS;

-- SELECIONANDO APENAS OS 5 PRIMEIROS REGISTROS
SELECT TOP 5 * FROM EVENTOS;

-- ORDENANDO
SELECT TOP 5 * FROM EVENTOS ORDER BY ID ASC;
SELECT TOP 5 * FROM EVENTOS ORDER BY ID DESC;

-- REALIZANDO FILTROS COM WHERE
SELECT * FROM EVENTOS WHERE TITULO = 'EVENTO A';
SELECT * FROM EVENTOS WHERE ID = 7;

-- UTILIZANDO DUAS CONDICOES NO WHERE
SELECT * FROM EVENTOS WHERE ID = 7 AND TITULO = 'EVENTO E';
SELECT * FROM EVENTOS WHERE ID = 5 OR TITULO = 'EVENTO E';
SELECT * FROM EVENTOS WHERE NOT ID = 2;

-- PARA VALORES NAO FIXADOS, PODE-SE USAR O LIKE
-- EM QUALQUER PARTE
SELECT * FROM EVENTOS WHERE TITULO LIKE '%A%';
-- COMECA COM E
SELECT * FROM EVENTOS WHERE TITULO LIKE 'E%';
-- TERMINA COM A
SELECT * FROM EVENTOS WHERE TITULO LIKE '%A';

-- SELECIONANDO AS DATAS
SELECT MIN(DATA_EVENTO) AS PRIMEIRA_APRESENTACAO FROM EVENTOS;
SELECT MAX(DATA_EVENTO) AS ULTIMA_APRESENTACAO FROM EVENTOS;

-- PODE-SE SELECIONAR DATAS ENTRE UM DETERMINADO VALOR
SELECT * FROM EVENTOS WHERE ID BETWEEN 4 AND 7;

SELECT * FROM EVENTOS WHERE DATA_EVENTO BETWEEN 
	CONVERT(DATETIME,'2019-03-18',120) AND CONVERT(DATETIME,'2019-03-21',120);

-- PODE-SE SELECIONAR DATA MAIORES OU MENORES
SELECT * FROM EVENTOS WHERE ID >= 10;
SELECT * FROM EVENTOS WHERE ID > 10;
SELECT * FROM EVENTOS WHERE ID < 10;
SELECT * FROM EVENTOS WHERE ID <= 10;

-- PODE-SE AGRUPAR VALORES POR ALGUMA COLUNA
SELECT COUNT(ID) AS QUANTIDADE_EVENTOS, ACESSO_LIVRE FROM EVENTOS GROUP BY ACESSO_LIVRE;

-- UTILIZANDO JOIN
SELECT E.*, C.*, U.* FROM EVENTOS E
INNER JOIN CONVITES C
ON E.ID = C.ID_EVENTO
INNER JOIN USUARIOS U
ON C.ID_USUARIO = U.ID;
-- AND C.PALESTRANTE = 1;

SELECT E.*, C.*, U.* FROM EVENTOS E
INNER JOIN CONVITES C
ON E.ID = C.ID_EVENTO
LEFT JOIN USUARIOS U
ON C.ID_USUARIO = U.ID;

SELECT E.*, C.*, U.* FROM EVENTOS E
INNER JOIN CONVITES C
ON E.ID = C.ID_EVENTO
RIGHT JOIN USUARIOS U
ON C.ID_USUARIO = U.ID;

SELECT U.*, E.* FROM USUARIOS U
INNER JOIN ENDERECOS E
ON U.ID_ENDERECO = E.ID;

SELECT E.ID AS ID_EVENTO, E.TITULO AS TITULO, E.DESCRICAO AS DESCRICAO, U.NOME AS PALESTRANTE FROM EVENTOS E INNER JOIN CONVITES C ON E.ID = C.ID_EVENTO INNER JOIN USUARIOS U ON C.ID_USUARIO = U.ID;