/* CRIAR UM BANCO DE DADOS - SINTAXE : CREATE DATABASE [NOME_BANCO] */
CREATE DATABASE SVIGUFO;

/* COLOCAR O BANCO DE DADOS CRIADO EM USO */
USE SVIGUFO;

-- CRIAR INSTITUICAO - ESCOLA SENAI DE INFORMATICA
CREATE TABLE INSTITUICOES (
	ID				INT IDENTITY PRIMARY KEY
	,RAZAO_SOCIAL	VARCHAR(255) NOT NULL
	,NOME_FANTASIA	VARCHAR(255)
	,CNPJ			CHAR(14) NOT NULL UNIQUE
	,LOGRADOURO     VARCHAR(200) NOT NULL
    ,CEP            CHAR(8) NOT NULL
    ,UF             CHAR(2) 
    ,CIDADE         VARCHAR(200)
);

-- CRIAR TABELA DE TIPOS DE EVENTOS (TECNOLOGIA, EDUCACAO, DESIGN, MARKETING)
CREATE TABLE TIPOS_EVENTOS (
    ID          INT IDENTITY PRIMARY KEY
    ,TITULO     VARCHAR(250) NOT NULL
);

-- CRIAR TABELA DE EVENTOS - COM DESCRICAO E INFORMANDO SE O EVENTO EH PUBLICO OU PRIVADO
CREATE TABLE EVENTOS (
    ID              INT IDENTITY PRIMARY KEY
    ,TITULO         VARCHAR(250) NOT NULL
    ,DESCRICAO      TEXT
    ,DATA_EVENTO    DATETIME
    ,DATA_CADASTRO  DATE
    ,ACESSO_LIVRE   BIT
    ,ID_TIPO_EVENTO INT -- FOREIGN KEY REFERENCES TIPOS_EVENTOS(ID)
    , FOREIGN KEY (ID_TIPO_EVENTO) REFERENCES TIPOS_EVENTOS(ID)
);

-- UNIQUE EMAIL
-- DEFAULT (0)

-- CRIAR TABELA DE USUARIOS QUE IRAO INTERAGIR - PODE SER COMUM OU ADMINISTRADOR
CREATE TABLE USUARIOS (
    ID              INT IDENTITY PRIMARY KEY
    ,NOME           VARCHAR(200) NOT NULL
    ,EMAIL          VARCHAR(254) NOT NULL
    ,SENHA          VARCHAR(100) NOT NULL
    ,TIPO_USUARIO   VARCHAR(50) NOT NULL
);

-- CADA EVENTO TERA UM PALESTRANTE / SERA UM USUARIO DO SISTEMA
ALTER TABLE EVENTOS
ADD ID_PALESTRANTE INT FOREIGN KEY REFERENCES USUARIOS(ID);

-- CRIAR A TABELA DE ENDERECOS - CADA USUARIO TERA SEU ENDERECO
CREATE TABLE ENDERECOS (
    ID              INT IDENTITY PRIMARY KEY
    ,LOGRADOURO     VARCHAR(200) NOT NULL
    ,CEP            CHAR(8) NOT NULL
    ,UF             CHAR(2) 
    ,CIDADE         VARCHAR(200) 
    ,LATITUDE       VARCHAR(20) NULL
    ,LONGITUDE      VARCHAR(20) NULL
);

ALTER TABLE USUARIOS
ADD ID_ENDERECO INT FOREIGN KEY REFERENCES ENDERECOS(ID);

-- OS CONVITES PODEM SER ENVIADOS PARA USUARIOS RELACIONADOS A EVENTOS
CREATE TABLE CONVITES (
    ID_USUARIO          INT FOREIGN KEY REFERENCES USUARIOS(ID)
    ,ID_EVENTO          INT FOREIGN KEY REFERENCES EVENTOS(ID)
);