DROP DATABASE SPMEDGROUP;

CREATE DATABASE SPMEDGROUP;
USE SPMEDGROUP;

-- ESPECIALIDADES
-- TIPOS_DOENCAS
-- PACIENTES
-- ADMINISTRADORES
-- MEDICOS
-- CONSULTAS
-- PRONTUARIOS

CREATE TABLE ESPECIALIDADES (
    ID      INT IDENTITY PRIMARY KEY
    ,NOME   VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE TIPOS_DOENCAS (
    ID      INT IDENTITY PRIMARY KEY
    ,NOME   VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE PACIENTES (
    ID                  INT IDENTITY PRIMARY KEY
    ,NOME               VARCHAR(200) NOT NULL
    ,EMAIL              VARCHAR(254) NOT NULL UNIQUE
    ,SENHA              VARCHAR(255) NOT NULL
    ,DATA_NASCIMENTO    DATE
    ,GENERO             VARCHAR(20)
    ,CPF                CHAR(11) UNIQUE
);

CREATE TABLE ADMINISTRADORES (
     ID                  INT IDENTITY PRIMARY KEY
    ,NOME               VARCHAR(200) NOT NULL
    ,EMAIL              VARCHAR(254) NOT NULL UNIQUE
    ,SENHA              VARCHAR(255) NOT NULL
);

CREATE TABLE MEDICOS (
     ID                 INT IDENTITY PRIMARY KEY
    ,NOME               VARCHAR(200) NOT NULL
    ,EMAIL              VARCHAR(254) NOT NULL UNIQUE
    ,SENHA              VARCHAR(255) NOT NULL
    ,CRM                CHAR(6) NOT NULL
    ,ID_ESPECIALIDADE   INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID)
);

CREATE TABLE CONSULTAS (
    ID                  INT IDENTITY PRIMARY KEY
    ,VALOR_CONSULTA     FLOAT DEFAULT(0)
    ,DATA_CONSULTA      DATETIME NOT NULL
    ,RETORNO            BIT
    ,ID_PACIENTE        INT FOREIGN KEY REFERENCES PACIENTES (ID)
    ,ID_MEDICO          INT FOREIGN KEY REFERENCES MEDICOS (ID)
);

CREATE TABLE PRONTUARIOS (
    ID              INT IDENTITY PRIMARY KEY
    ,DESCRICAO      TEXT NOT NULL
    ,ID_CONSULTA    INT FOREIGN KEY REFERENCES CONSULTAS (ID)
    ,ID_TIPO_DOENCA INT FOREIGN KEY REFERENCES TIPOS_DOENCAS (ID)
);