DROP DATABASE SPMEDGROUP;

CREATE DATABASE SPMEDGROUP;
USE SPMEDGROUP;

-- CLINICAS
-- ESPECIALIDADES
-- PRONTUARIOS
-- USUARIOS
-- MEDICOS
-- CONSULTAS

CREATE TABLE ESPECIALIDADES (
    ID      INT IDENTITY PRIMARY KEY
    ,NOME   VARCHAR(200) NOT NULL UNIQUE
);
GO

CREATE TABLE CLINICAS (
    ID      INT IDENTITY PRIMARY KEY
    ,NOME   VARCHAR(200) NOT NULL UNIQUE
);
GO

CREATE TABLE USUARIOS (
     ID                 INT IDENTITY PRIMARY KEY
    ,EMAIL              VARCHAR(254) NOT NULL UNIQUE
    ,SENHA              VARCHAR(255) NOT NULL
    ,TIPO_USUARIO       VARCHAR(30) NOT NULL
);
GO

CREATE TABLE MEDICOS (
     ID                 INT IDENTITY PRIMARY KEY
    ,NOME               VARCHAR(200) NOT NULL
    ,CRM                CHAR(6) NOT NULL
    ,ID_ESPECIALIDADE   INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID)
    ,ID_CLINICA         INT FOREIGN KEY REFERENCES CLINICAS(ID)
    ,ID_USUARIO         INT FOREIGN KEY REFERENCES USUARIOS(ID)
);
GO

CREATE TABLE PRONTUARIOS (
    ID                  INT IDENTITY PRIMARY KEY
    ,NOME               VARCHAR(200) NOT NULL
    ,DATA_NASCIMENTO    DATE
    ,GENERO             VARCHAR(20)
    ,CPF                CHAR(11) UNIQUE
    ,ID_USUARIO         INT UNIQUE FOREIGN KEY REFERENCES USUARIOS(ID)
);
GO

CREATE TABLE CONSULTAS (
    ID                  INT IDENTITY PRIMARY KEY
    ,DATA_CONSULTA      DATETIME NOT NULL
    ,SITUACAO           CHAR(1) DEFAULT(1)
    ,DESCRICAO          TEXT NULL
    ,RETORNO            BIT DEFAULT(0)
    ,ID_PRONTUARIO      INT FOREIGN KEY REFERENCES PRONTUARIOS (ID)
    ,ID_MEDICO          INT FOREIGN KEY REFERENCES MEDICOS (ID)
);
GO